version: "3"
services:
    web:
        build: frontend/
        expose:
            - "8080"
        restart: "always"

    nginx:
        image: nginx:1.19
        volumes:
            - ./data/nginx:/etc/nginx/conf.d
            - ./data/certbot/conf:/etc/letsencrypt
            - ./data/certbot/www:/var/www/certbot
        ports:
            - "80:80"
            - "443:443"
        restart: "always"
        command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

    certbot:
        image: certbot/certbot
        volumes:
            - ./data/certbot/conf:/etc/letsencrypt
            - ./data/certbot/www:/var/www/certbot
        restart: "always"
        entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

    backend:
        build: backend/
        restart: "always"

    mongodb:
        image: mongo
        volumes:
            - ./mongo-data:/data/db:rw
        environment:
            - MONGO_DATA_DIR=/data/db/geezdb
        restart: "always"

volumes:
  mongo-data:
